"use client";

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FileBarChart, ExternalLink, X } from "lucide-react";
import { useAgentStore } from "@/stores/agentStore";

export function LiveReportToaster() {
  const [report, setReport] = useState<{ id: string; agentId: string; title: string } | null>(null);
  const decisions = useAgentStore((s) => s.decisions);

  useEffect(() => {
    // Listen for agent decisions that are generating a report
    const latest = decisions[decisions.length - 1];
    if (latest && latest.action && latest.action.toLowerCase().includes("report")) {
      const newReport = {
        id: Math.random().toString(36).substring(7),
        agentId: latest.agentId || "Reporter Agent",
        title: latest.action,
      };
      setReport(newReport);
      
      // Auto-hide after 5 seconds
      const timer = setTimeout(() => {
        setReport(null);
      }, 5000);
      return () => clearTimeout(timer);
    }
  }, [decisions]);

  return (
    <div className="fixed bottom-6 right-6 z-50 flex flex-col items-end gap-2">
      <AnimatePresence>
        {report && (
          <motion.div
            initial={{ opacity: 0, y: 50, scale: 0.9 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, scale: 0.9, x: 20 }}
            className="bg-black/80 backdrop-blur-xl border border-blue-500/30 rounded-xl p-4 shadow-[0_0_30px_rgba(10,132,255,0.2)] w-80 relative overflow-hidden"
          >
            {/* Shimmer effect */}
            <div className="absolute top-0 left-[-100%] w-full h-full bg-gradient-to-r from-transparent via-white/10 to-transparent animate-[shimmer_2s_infinite]" />
            
            <button 
              onClick={() => setReport(null)}
              className="absolute top-2 right-2 text-white/40 hover:text-white transition"
            >
              <X className="w-4 h-4" />
            </button>
            
            <div className="flex gap-3">
              <div className="mt-1 bg-blue-500/20 p-2 rounded-lg h-fit border border-blue-500/30">
                <FileBarChart className="w-5 h-5 text-blue-400" />
              </div>
              <div className="flex-1">
                <div className="text-xs text-blue-400 font-semibold mb-1 tracking-wider uppercase flex items-center gap-2">
                  <span className="relative flex h-2 w-2">
                    <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-blue-400 opacity-75" />
                    <span className="relative inline-flex h-2 w-2 rounded-full bg-blue-500" />
                  </span>
                  Live Report Ready
                </div>
                <div className="font-medium text-sm mb-1">{report.title}</div>
                <div className="text-xs text-white/50 mb-3">Generated by {report.agentId}</div>
                
                <button className="flex items-center gap-1.5 text-xs text-white bg-blue-600 hover:bg-blue-500 transition px-3 py-1.5 rounded-md w-full justify-center shadow-[0_0_15px_rgba(10,132,255,0.4)]">
                  <ExternalLink className="w-3.5 h-3.5" />
                  View Full Report
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
