"""PDF export service. Provides structured layout data for client-side jsPDF rendering."""

from datetime import datetime


class PDFExporter:
    async def export_report(self, report: dict, format: str = "json") -> dict:
        return {
            "report": report,
            "export_metadata": {"format": format, "exported_at": datetime.utcnow().isoformat(), "exporter_version": "2.0"},
            "layout": self._generate_layout(report),
        }

    def _generate_layout(self, report: dict) -> dict:
        report_type = report.get("type", "incident")
        sections = []

        sections.append({"type": "title_page", "content": {
            "title": self._get_title(report), "report_id": report.get("report_id"),
            "date": report.get("generated_at", "")[:10],
            "classification": report.get("metadata", {}).get("classification", "INTERNAL"),
        }})

        if "executive_summary" in report:
            s = report["executive_summary"]
            sections.append({"type": "summary_table", "title": "Executive Summary", "rows": [
                {"label": "Incident Type", "value": s.get("incident_type", "")},
                {"label": "Severity", "value": s.get("severity", "").upper()},
                {"label": "Segment", "value": s.get("segment", "")},
                {"label": "Passengers Protected", "value": f"{s.get('passengers_protected', 0):,}"},
                {"label": "AI Confidence", "value": f"{s.get('ai_confidence_avg', 0)}%"},
            ]})

        if "incident_timeline" in report:
            sections.append({"type": "timeline", "title": "Incident Timeline", "entries": report["incident_timeline"]})

        if "agent_decisions" in report:
            sections.append({"type": "decisions_table", "title": "Agent Decisions & Reasoning", "decisions": report["agent_decisions"]})

        if "outcome_metrics" in report:
            m = report["outcome_metrics"]
            sections.append({"type": "metrics_grid", "title": "Outcome Metrics", "metrics": [
                {"label": "Passengers Protected", "value": f"{m.get('passengers_protected', 0):,}"},
                {"label": "Delay Prevented", "value": f"{m.get('delay_prevented_hours', 0)}h"},
                {"label": "Cost Saved", "value": f"₹{m.get('estimated_cost_saved_inr', 0):,}"},
                {"label": "Safety Score", "value": m.get("safety_score", "N/A")},
            ]})

        if "recommendations" in report:
            sections.append({"type": "recommendations", "title": "Recommendations", "items": report["recommendations"]})

        return {
            "page_size": "A4", "margins": {"top": 20, "right": 15, "bottom": 20, "left": 15},
            "header": {"title": f"RailNerv Sentinel — {report_type.title()} Report", "subtitle": report.get("report_id", "")},
            "footer": {"text": f"Generated by RailNerv Sentinel v2.0 — {report.get('generated_at', '')}", "page_numbers": True},
            "sections": sections,
            "styling": {"primary_color": "#0a84ff", "critical_color": "#ff453a", "warning_color": "#ffd60a", "normal_color": "#30d158"},
        }

    def _get_title(self, report: dict) -> str:
        t = report.get("type", "report")
        if t == "incident":
            s = report.get("executive_summary", {})
            return f"{s.get('incident_type', 'Incident').replace('_', ' ').title()} — {s.get('segment', 'Unknown')}"
        return f"{t.title()} Report"
